# The VIP Path
Tujuan :

## 1. Overview
Tujuan : Melihat sekilas bentuk dataset.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv("dataset-pelanggan.csv")
df.head()

,Unnamed: 0,id_pelanggan,jam_main_mingguan,genre_favorit,pengeluaran_snack,waktu_main_utama,hardware_requirement,vip_lounge_visit,target_membership
0,0,1,23.10,FPS,22000,Subuh,1,1,0
1,1,2,4.43,Casual,37000,Sore,0,1,0
2,2,3,56.37,MOBA,22000,Subuh,1,16,0
3,3,4,31.96,RPG,18000,Sore,0,19,0
4,4,5,23.57,Casual,61000,Sore,1,4,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            1000 non-null   int64
 1   id_pelanggan          1000 non-null   int64
 2   jam_main_mingguan     1000 non-null   float64
 3   genre_favorit         1000 non-null   object
 4   pengeluaran_snack     1000 non-null   int64
 5   waktu_main_utama      1000 non-null   object
 6   hardware_requirement  1000 non-null   int64
 7   vip_lounge_visit      1000 non-null   int64
 8   target_membership     1000 non-null   int64
dtypes: float64(1), int64(6), object(2)
memory usage: 70.4+ KB

In [3]:
df.tail()

,Unnamed: 0,id_pelanggan,jam_main_mingguan,genre_favorit,pengeluaran_snack,waktu_main_utama,hardware_requirement,vip_lounge_visit,target_membership
995,995,996,48.33,Casual,62000,Sore,0,15,0
996,996,997,45.62,MOBA,24000,Malam,0,19,0
997,997,998,42.26,MOBA,66000,Siang,1,6,0
998,998,999,52.68,FPS,77000,Siang,0,14,0
999,999,1000,56.83,RPG,69000,Sore,1,15,0